<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.6pASezJ' shared service.

return $this->privates['.service_locator.6pASezJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.wyrb61.', 'get_ServiceLocator_Wyrb61_Service.php', true],
    'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.EbLunuf', 'get_ServiceLocator_EbLunufService.php', true],
    'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.wyrb61.', 'get_ServiceLocator_Wyrb61_Service.php', true],
    'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.EbLunuf', 'get_ServiceLocator_EbLunufService.php', true],
], [
    'App\\Controller\\RegistrationController::register' => '?',
    'App\\Controller\\SecurityController::login' => '?',
    'App\\Controller\\RegistrationController:register' => '?',
    'App\\Controller\\SecurityController:login' => '?',
]);
